/**
 * Market types for screeners
 */
export const Market = {
  AMERICA: 'america',
  UK: 'uk',
  AUSTRALIA: 'australia',
  CANADA: 'canada',
  GERMANY: 'germany',
  FRANCE: 'france',
  SPAIN: 'spain',
  ITALY: 'italy',
  POLAND: 'poland',
  TURKEY: 'turkey',
  BRAZIL: 'brazil',
  MEXICO: 'mexico',
  INDIA: 'india',
  INDONESIA: 'indonesia',
  KOREA: 'korea',
  JAPAN: 'japan',
  HONGKONG: 'hongkong',
  SINGAPORE: 'singapore',
  SWITZERLAND: 'switzerland',
  BELGIUM: 'belgium',
  CHILE: 'chile',
  NEWZEALAND: 'newzealand',
  SWEDEN: 'sweden',
  ISRAEL: 'israel',
  NETHERLANDS: 'netherlands',
  MALAYSIA: 'malaysia',
  TAIWAN: 'taiwan',
  THAILAND: 'thailand',
  CHINA: 'china',
  VIETNAM: 'vietnam',
  BAHRAIN: 'bahrain',
  COLOMBIA: 'colombia',
  EGYPT: 'egypt',
  FINLAND: 'finland',
  GREECE: 'greece',
  NORWAY: 'norway',
  PHILIPPINES: 'philippines',
  PORTUGAL: 'portugal',
  QATAR: 'qatar',
  RSA: 'rsa',
  SRILANKA: 'srilanka',
  UAE: 'uae',
  ARGENTINA: 'argentina',
  AUSTRIA: 'austria',
  BANGLADESH: 'bangladesh',
  CYPRUS: 'cyprus',
  DENMARK: 'denmark',
  ESTONIA: 'estonia',
  ICELAND: 'iceland',
  LUXEMBOURG: 'luxembourg',
  MOROCCO: 'morocco',
  PAKISTAN: 'pakistan',
  PERU: 'peru',
  ROMANIA: 'romania',
  SERBIA: 'serbia',
  VENEZUELA: 'venezuela',
} as const;

export type MarketValue = typeof Market[keyof typeof Market];
